### ISSUE TITLE
Allow import and export of DOT files

### ISSUE THREAD

**Issue by jmiezitis** [magjac/graphviz-visual-editor#129] opened 2020-01-30 22:42 UTC
This would allow DOT files from other sources to be loaded into graphviz-visual-editor and take the modified file back out to use in other utilities e.g. Cumulus [Topology_Converter](https://github.com/CumulusNetworks/topology_converter)

**Comment by magjac** [comment] 2020-01-31 07:39
Thanks for your suggestion. Is https://github.com/magjac/graphviz-visual-editor/issues/81 what you want?

**Comment by jmiezitis** [comment] 2020-02-01 06:31
I wasn'y sure if by "Browser's local storage" you meant it would still be in sqlite.
If not and the file .dot file will appear in the local file system then yes that is what I want.

**Comment by magjac** [comment] 2020-02-02 18:34
I don't know why you mention sqlite. It is not used by this application. If you follow the "local storage" link in https://github.com/magjac/graphviz-visual-editor/issues/81 you come to
https://developer.mozilla.org/en-US/docs/Web/API/Window/localStorage. That's what is meant by  "Browser's local storage".

Anyway, as I understand it you want to be able to export to and import from the local file system and that is exactly what https://github.com/magjac/graphviz-visual-editor/issues/81 is about.

I will look into implementing this shortly.

**Comment by powderluv** [comment] 2020-09-03 03:06
Agreed. This would be a great addition to import .dot files from the filesystem (not just browser local storage) and save them back.

**Comment by magjac** [comment] 2020-09-03 07:56
From what I understand, this a duplicate of #81. Please reopen if I'm mistaken.

**Closed by magjac** 2020-09-03 07:56 UTC
Labels: duplicate, enhancement

**Comment by powderluv** [comment] 2020-09-03 14:24
Yes yes. They are the same. Will track it there
