### ISSUE TITLE
Having a node called `toString` hard crashes the editor

### ISSUE THREAD

**Issue by ferrybig** [magjac/graphviz-visual-editor#272] opened 2024-02-08 09:28 UTC
1. Go to http://magjac.com/graphviz-visual-editor/
2. Paste the following graph:
```
strict digraph G {
  a -> toString;
  toString -> a;
}
```

# Expected:

It renders 2 nodes, called `a` and `toString` and draws arrows between them, as shows with other tools like https://dreampuf.github.io/GraphvizOnline/#strict%20digraph%20G%20%7B%0A%20%20%0A%20%20a%20-%3E%20toString%3B%0A%20%20toString%20-%3E%20a%3B%0A%7D

# Actual

The whole page turns white and it logs the following error to the console:

```
Uncaught TypeError: this.nodes[o].locations is undefined
```

**Comment by magjac** [comment] 2024-02-11 09:41
Thanks for the report. This bug has the same root cause as https://github.com/magjac/graphviz-visual-editor/issues/265. I have a fix available, but it exposed a similar [d3-graphviz issue](https://github.com/magjac/d3-graphviz/issues/301) which I have fixed, but not made any release of it yet, since I'm waiting for the new [Graphviz 10.0.1 release](https://gitlab.com/graphviz/graphviz/-/blob/main/CHANGELOG.md?ref_type=heads#1001-2024-02-11) to be available in [hpcc-js-wasm ](https://github.com/hpcc-systems/hpcc-js-wasm) which d3-graphviz depends on. It should imminent, but these been some hickup that is being discussed [here](https://github.com/hpcc-systems/hpcc-js-wasm/issues/210#issuecomment-1937355780) and [here](https://gitlab.com/graphviz/graphviz/-/merge_requests/3464#note_1767706931).

**Comment by magjac** [comment] 2024-02-11 17:31
Fixed by https://github.com/magjac/graphviz-visual-editor/pull/277.

**Closed by magjac** 2024-02-11 17:31 UTC
Labels: bug
